use crate::types::{CommandConfidence, SafetyClass};
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum CommandId {
    GetPid,
    GetReportRevision,
    GetMode,
    GetModeAlt,
    GetControllerVersion,
    GetSuperButton,
    SetModeDInput,
    Idle,
    Version,
    ReadProfile,
    WriteProfile,
    EnterBootloaderA,
    EnterBootloaderB,
    EnterBootloaderC,
    ExitBootloader,
    FirmwareChunk,
    FirmwareCommit,
    Jp108ReadDedicatedMappings,
    Jp108WriteDedicatedMapping,
    Jp108ReadFeatureFlags,
    Jp108WriteFeatureFlags,
    Jp108ReadVoice,
    Jp108WriteVoice,
    U2GetCurrentSlot,
    U2ReadConfigSlot,
    U2WriteConfigSlot,
    U2ReadButtonMap,
    U2WriteButtonMap,
    U2SetMode,
    Jp108EnterBootloader,
    Jp108FirmwareChunk,
    Jp108FirmwareCommit,
    Jp108ExitBootloader,
    U2EnterBootloader,
    U2FirmwareChunk,
    U2FirmwareCommit,
    U2ExitBootloader,
}

impl CommandId {
    pub const ALL: [CommandId; 37] = [
        CommandId::GetPid,
        CommandId::GetReportRevision,
        CommandId::GetMode,
        CommandId::GetModeAlt,
        CommandId::GetControllerVersion,
        CommandId::GetSuperButton,
        CommandId::SetModeDInput,
        CommandId::Idle,
        CommandId::Version,
        CommandId::ReadProfile,
        CommandId::WriteProfile,
        CommandId::EnterBootloaderA,
        CommandId::EnterBootloaderB,
        CommandId::EnterBootloaderC,
        CommandId::ExitBootloader,
        CommandId::FirmwareChunk,
        CommandId::FirmwareCommit,
        CommandId::Jp108ReadDedicatedMappings,
        CommandId::Jp108WriteDedicatedMapping,
        CommandId::Jp108ReadFeatureFlags,
        CommandId::Jp108WriteFeatureFlags,
        CommandId::Jp108ReadVoice,
        CommandId::Jp108WriteVoice,
        CommandId::U2GetCurrentSlot,
        CommandId::U2ReadConfigSlot,
        CommandId::U2WriteConfigSlot,
        CommandId::U2ReadButtonMap,
        CommandId::U2WriteButtonMap,
        CommandId::U2SetMode,
        CommandId::Jp108EnterBootloader,
        CommandId::Jp108FirmwareChunk,
        CommandId::Jp108FirmwareCommit,
        CommandId::Jp108ExitBootloader,
        CommandId::U2EnterBootloader,
        CommandId::U2FirmwareChunk,
        CommandId::U2FirmwareCommit,
        CommandId::U2ExitBootloader,
    ];

    pub fn all() -> &'static [CommandId] {
        &Self::ALL
    }
}

#[derive(Clone, Debug)]
pub struct CommandDefinition {
    pub id: CommandId,
    pub safety_class: SafetyClass,
    pub confidence: CommandConfidence,
    pub experimental_default: bool,
    pub report_id: u8,
    pub request: &'static [u8],
    pub expected_response: &'static str,
}
